### ISSUE TITLE
Better detection of user-defined line heights

### ISSUE THREAD

**Issue by andyhernandez** [jkeck/responsiveTruncator#2]
In order to account for non-standard line-heights set by the user, you need to first detect whether a css line-height exists or not.

on line 24 replace:
var lineHeight = Math.floor(parseInt(fontSize.replace('px','')) \* 1.5);

with:
var lineHeight = $(this).css("line-height") ? $(this).css("line-height").replace('px','') : Math.floor(parseInt(fontSize.replace('px','')) \* 1.5);

**Comment by jkeck** [comment]
Thanks for pointing this out!  This has been added in 527ad5c42f789639467aff88da3f98093dcba70e.
